version: '3.7'

services:
  web:
    build: ./back-end
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./back-end/:/usr/src/app/
    ports:
      - 1337:8000
    env_file:
      - ./back-end/.env
    environment:
      - DEBUG=1
      - SECRET_KEY=${SECRET_KEY}
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
    depends_on:
      - redis
  redis:
    image: redis:alpine
  celery:
    build: ./back-end
    command: celery -A core worker -l info
    volumes:
      - ./back-end/:/usr/src/app/
    environment:
      - DEBUG=1
      - SECRET_KEY=${SECRET_KEY}
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
    depends_on:
      - redis
  celery-beat:
    build: ./back-end
    command: celery -A core beat -l info
    volumes:
      - ./back-end/:/usr/src/app/
    environment:
      - DEBUG=1
      - SECRET_KEY=${SECRET_KEY}
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
    depends_on:
      - redis
